# Site settings
title:       blog
email:       bgschiller@gmail.com
author:      Brian Schiller
description: "Writings on Mathematics, Software, and Teaching."
baseurl:     "/pixyll"
url:         "http://brianschiller.com"

# Google analytics
google_analytics: UA-53548208-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
sass:
  compressed: true
